### ISSUE TITLE
Generating QR / barcodes

### ISSUE THREAD

**Issue by r-kaminski** [nokia-wroclaw/innovativeproject-inventory-of-supplies#6]
QR / barcodes should be either generated once and stored in database or generated every time they're accessed from application (the generation time might be lesser than accessing remote database - this is yet to be decided).

**Comment by KBialecki** [comment]
Added the ability to print QR codes using Pillow and PyQRCode. Returns an A4 sized image at 300 dpi with maximum 110 codes with their ids. Codes should be around 2 cm x 2 cm after printing (including the border generated by PyQRCode). Due to issues with loading a seperate font file a default one (already built in PIL) is used.
